feat: add new tour query param
Focus-Bear/assets pull request #274
Opened 2024-11-06 14:57 UTC by amanueltsfy

## Issues
![image](https://github.com/user-attachments/assets/da45f397-68a9-4e2e-8690-e99e968ef8cc)
![image](https://github.com/user-attachments/assets/d6160115-509e-491a-abae-c913f1ce0d15)

## Test
![image](https://github.com/user-attachments/assets/20fe1925-f957-4fde-93b0-bcf67d8b3798)

2024-11-06 21:35 UTC, jeznag commented
@amanueltsfy can you fix the json file issue?

2024-11-07 11:53 UTC, amanueltsfy commented
> @amanueltsfy can you fix the json file issue?

done

2024-11-12 05:04 UTC, jeznag commented on focus-blocked/js/main.js
> +  console.log(focusRemainingSeconds, shouldActivateAlwaysBlock);
delete

2024-11-12 05:06 UTC, jeznag requested changes
a few minor changes

2024-11-12 05:06 UTC, jeznag commented on README.md
> +### .github\workflow\main.yml
Is this needed?

2024-11-12 05:06 UTC, jeznag commented on README.md
> +## **Perform the following before updating the config-es.json or confign.json files**
Is any of this still necessary? We're not doing repo forking anymore

2024-11-12 05:06 UTC, jeznag commented on .prettierignore
> +.github
trailing new line

2024-11-12 08:42 UTC, amanueltsfy commented on README.md
> +### .github\workflow\main.yml
will remove it

2024-11-13 23:05 UTC, jeznag commented on .github/workflows/needstranslation.yml
@amanueltsfy I think you have changed the behaviour of this check. It's still helpful to see if there are keys needing translation but maybe it can be configured so it's a soft failure and we can still merge even if translations are required

2024-11-13 23:06 UTC, jeznag commented on .github/workflows/check-json.sh
> +fi
Please add trailing new line

2024-11-13 23:06 UTC, jeznag commented on .github/workflows/main.yml
> +          bash ./.github/workflows/check-json.sh
Please add trailing new line

2024-11-13 23:06 UTC, jeznag commented on .github/workflows/needstranslation.yml
> +          bash ./.github/workflows/check-json.sh
Please add trailing new line

2024-11-13 23:06 UTC, jeznag commented on .gitignore
> +.history
Please add trailing new line

2024-11-13 23:07 UTC, jeznag commented on README.md
I don't think we should delete it. We should add a meaningful readme that explains what this repo is used for

2024-11-14 23:10 UTC, jeznag commented on .github/workflows/main.yml
> +
still missing trailing new line. Please configure your editor to automatically add it.

2024-11-14 23:10 UTC, jeznag commented on .gitignore
> +.history
not done

2024-11-14 23:11 UTC, jeznag commented on .github/workflows/needstranslation.yml
@amanueltsfy feedback was not actioned

2024-11-22 04:43 UTC, jeznag reviewed
https://github.com/Focus-Bear/assets/blob/main/.github/workflows/needstranslation.yml - continue on error = true

2024-11-22 19:53 UTC, jeznag approved these changes

2024-11-23 09:20 UTC, merged